/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessNetworkRouteImport } from './routes/business-network'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessNetworkIndexRouteImport } from './routes/business-network.index'
import { Route as BusinessNetworkSlugRouteImport } from './routes/business-network.$slug'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNetworkRoute = BusinessNetworkRouteImport.update({
  id: '/business-network',
  path: '/business-network',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNetworkIndexRoute = BusinessNetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessNetworkRoute,
} as any)
const BusinessNetworkSlugRoute = BusinessNetworkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessNetworkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/business-network': typeof BusinessNetworkRouteWithChildren
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/business-network/$slug': typeof BusinessNetworkSlugRoute
  '/business-network/': typeof BusinessNetworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/business-network/$slug': typeof BusinessNetworkSlugRoute
  '/business-network': typeof BusinessNetworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/business-network': typeof BusinessNetworkRouteWithChildren
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/business-network/$slug': typeof BusinessNetworkSlugRoute
  '/business-network/': typeof BusinessNetworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/business-network'
    | '/contact'
    | '/franchise'
    | '/gallery'
    | '/business-network/$slug'
    | '/business-network/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/franchise'
    | '/gallery'
    | '/business-network/$slug'
    | '/business-network'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/business-network'
    | '/contact'
    | '/franchise'
    | '/gallery'
    | '/business-network/$slug'
    | '/business-network/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  BusinessNetworkRoute: typeof BusinessNetworkRouteWithChildren
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  GalleryRoute: typeof GalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-network': {
      id: '/business-network'
      path: '/business-network'
      fullPath: '/business-network'
      preLoaderRoute: typeof BusinessNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-network/': {
      id: '/business-network/'
      path: '/'
      fullPath: '/business-network/'
      preLoaderRoute: typeof BusinessNetworkIndexRouteImport
      parentRoute: typeof BusinessNetworkRoute
    }
    '/business-network/$slug': {
      id: '/business-network/$slug'
      path: '/$slug'
      fullPath: '/business-network/$slug'
      preLoaderRoute: typeof BusinessNetworkSlugRouteImport
      parentRoute: typeof BusinessNetworkRoute
    }
  }
}

interface BusinessNetworkRouteChildren {
  BusinessNetworkSlugRoute: typeof BusinessNetworkSlugRoute
  BusinessNetworkIndexRoute: typeof BusinessNetworkIndexRoute
}

const BusinessNetworkRouteChildren: BusinessNetworkRouteChildren = {
  BusinessNetworkSlugRoute: BusinessNetworkSlugRoute,
  BusinessNetworkIndexRoute: BusinessNetworkIndexRoute,
}

const BusinessNetworkRouteWithChildren = BusinessNetworkRoute._addFileChildren(
  BusinessNetworkRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  BusinessNetworkRoute: BusinessNetworkRouteWithChildren,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  GalleryRoute: GalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
